FROM ubuntu:18.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive && apt-get install -y tzdata
RUN apt-get install -y python3 python3-pip python3-tk

RUN python3 -m pip install grpcio grpcio-tools

COPY ./ /chat/

ENTRYPOINT ["python3", "/chat/main.py", "6061"] 
